### PR TITLE
fix a minor to-do item

### PR DESCRIPTION
**Pull request by slager**
resolves 1st TODO item from #12

### CODE REVIEW

**Comment by liannesheppard** [comment]
There was a minor merge conflict that I resolved.  However, now I don't see how to merge this back into the main branch.  Is it not ready yet?

**Comment by slager** [comment]
I see that you made a merge commit in the slager:todo1 branch. It looks good there.  There is no "Merge pull request" green button on this page now?

**Review by liannesheppard — APPROVED** [review]

**Comment by liannesheppard** [comment]
That worked.  I had to approve the changes and then make sure the merge pull request didn't default to rebase.

**Comment by slager** [comment]
Glad it worked. What do you mean re: making sure it didn't default to rebase? I'm curious how that works.

**Pull request merged**
