### PR TITLE
Week8

### PR DESCRIPTION
**Pull request by slager**
Hi Lianne,

I think it's going to simplify things quite a bit to use the sf package for everything instead of sp, which is a harder to use, doesn't play as nicely with ggplot2, and basically outdated at this point (I learned how to do geospatial stuff with sp too though!). My slager:week8 branch implements the sf code up through kriging, but not yet including CV.  Any chance you can clone my branch and test if it runs okay and generally looks to your satisfaction?  If this seems fine, I'll go ahead and use sf for the cross validation as well.  I'm just calling this a draft pull request for now.  You can clone my version and test it up through CV by using this code:

git clone -b week8 https://github.com/slager/ENVH556_2021course

Dave

### CODE REVIEW

**Comment by liannesheppard** [comment]
Dave,
I appreciate you implementing this with the sf package.  I had read that it was better than sp but wasn't in a place to implement it.  The changes look good.  I will try to get to testing this tomorrow.  I assume I clone this into a different project so it doesn't get mixed up with the current version. Thanks for your work.

**Comment by slager** [comment]
Hi Lianne,

Yes, you could either clone it into a different directory, or for something like this where it's just testing, you could even copy/paste this into a new .Rmd file in your own working directory to see if it works. I should add that I couldn't get the kriging to work with sp, so perhaps you could double-check that it seems to be working with sf.

Dave

https://raw.githubusercontent.com/slager/ENVH556_2021course/week8/Week8LabGeostatistics.Rmd

**Comment by liannesheppard** [comment]
The code works well until the chunk at line 580, the kriging CV.  The bubble plot fails so I commented it out.  But even so there is an error with the krige.cv calls.  Here is one error message:
---------
object has comment, which is lost in outputCRS object has comment, which is lost in outputCRS object has comment, which is lost in outputDiscarded datum Unknown based on Bessel 1841 ellipsoid in Proj4 definition
-------

**Comment by slager** [comment]
Ok good, I didn't expect it to work past line 580 because bubble() is an sp function. I just pushed a commit that fixes the CV section with a ggplot version of bubble(). I also fixed what I think were some typos involving using different object names for universal kriging. Maybe you can check if it seems to still look good and if so I'll start digging into the snapshot code.

https://github.com/slager/ENVH556_2021course/blob/0f2295dee935a6f585263b75f784bf83cd6d2ec5/Week8LabGeostatistics.Rmd#L580

**Comment by liannesheppard** [comment]
I tested your new sf implementation of kriging and I see that it appears to work and that there are distinct differences between the OK and UK residuals.  What puzzles me is that in the previous implementation there were some apparent differences in the residuals based on the 5-fold vs LOO implementations.  I don't see these differences in the plots any more so I'm wondering how the sf implementation is different and how it handles the folds.  Also I don't see that any of the plots correspond completely w.r.t. residual patterns and signs.  In particular, the OK residuals along the river were positive in the previous implementation while there is a strong distinct negative pattern along the river in the current implementation.  So something is really different.

**Comment by slager** [comment]
Not sure if it's the cause of the discrepancy, but there was a typo at https://github.com/liannesheppard/ENVH556_2021course/blob/64f7718f96aeef5f2625c4858986c32580f180d4/Week8LabGeostatistics.Rmd#L552 where there was a mismatch between what was being saved in the line above and what was being plotted.  I fixed that in https://github.com/slager/ENVH556_2021course/blob/0f2295dee935a6f585263b75f784bf83cd6d2ec5/Week8LabGeostatistics.Rmd#L623

**Comment by slager** [comment]
I just pushed another commit that makes it more explicit how the sign of the residual plots get colored. It still looks like  the ordinary kriging has more positive residuals near the river, whereas the residuals from the universal kriging are more clumped throughout.

I think it makes sense to me the way it is now, that the residuals would differ more by kriging type than by CV type.  Do you think that's right?

As for sp vs. sf, it shouldn't actually matter because krige.cv can read in either an sp or sf object (I didn't change how those functions were called).

Any more thoughts on this?

**Comment by slager** [comment]
I think this pull request is now ready for merging.  I have basically the whole lab working correctly with sf and projections, except for a few things noted in the email.  It should have no conflicts with the main branch. I could create additional pull request in future on a different feature branch if needed.

**Comment by slager** [comment]
Lianne,
I fixed a bug in my krige.cv.sf wrapper function.  You should see the differences you were expecting in the cross validations now.
Dave

**Pull request merged**
